# Generated by Django 4.0.5 on 2022-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Employee Name'),
        ),
    ]
