# Generated by Django 4.0.5 on 2022-07-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='band_placeholder.jpg', upload_to='avatars'),
        ),
    ]
