# Generated by Django 4.0.5 on 2022-07-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='event_placeholder.jpg', upload_to='event_photo'),
        ),
    ]
