# Generated by Django 4.0.5 on 2022-07-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specials',
        ),
    ]
